#define PIN_BUZZER 15

#define PIN_LED_RED 25
#define PIN_LED_GREEN 26
#define PIN_LED_BLUE 27

// TODO RFID RECHERCHIEREN

#define MOTOR_PWM 12

#define PIN_UNLOCK_BUTTON 33
#define PIN_LOCK_BUTTON 32