#define PIN_BUZZER 15

#define PIN_LED_RED 25
#define PIN_LED_GREEN 26
#define PIN_LED_BLUE 27

// TODO RFID RECHERCHIEREN

#define PIN_ACCELSENSOR A1

#define MOTOR_PWM 20

#define PIN_UNLOCK_BUTTON 12
#define PIN_LOCK_BUTTON 32